language: zh-CN
local: false
reward: true
qrcode: true

menu:
  home: /
  archives:
    categories: /categories/
    tags: /tags/
    archives: /archives/
  projects: /project/
  about: /about/

# highlight style
highlight: github

# Local search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1

about:
  avatar: https://avatars1.githubusercontent.com/u/558922?v=3&s=460
  description: A researcher of vector graphics and dynamic geometry techniques.
  email:
  weibo_username: rhcad
  github_username: rhcad
  #zhihu_username: